[package]
name = "todo_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version="1.0.215", features=["derive"] }
sqlx = { version = "0.8.2", features = ["mysql", "runtime-tokio-native-tls"] }
tokio = { version = "1.41.1", features = ["full"] }