str = "Suraj is a good boy"
#print(str[0:19: 2])
print(str.endswith("boy"))
print(str.isalpha())
print(str.isalnum())
print(str.replace("is","was"))
print(str.capitalize())
print(str.upper())
print(str.lower())
print(str.count("o"))